#!/bin/sh
# Change domain configuration to boot from storage configured by u-boot

DOMA_CFG_FILE="/etc/xen/doma.cfg"

# detect boot storage device
BOOT_STORAGE=`cat /proc/device-tree/boot_dev/device`
if [ -z "$BOOT_STORAGE" ] ; then
    BOOT_STORAGE=mmcblk1
    echo "WARNING! Using default storage: ${BOOT_STORAGE}"
fi

# Special case for NFS - we can't boot Android from NFS
if [ $BOOT_STORAGE = nfs ] ; then
    BOOT_STORAGE=mmcblk0
    echo "Using eMMC storage: ${BOOT_STORAGE} instead of NFS"
fi

# guess partition prefix, e.g. "" for sda2 or "p" for mmcblk1p3
PART_PREFIX=""
if echo "${BOOT_STORAGE}" | grep -q 'mmc' ; then
   PART_PREFIX="p"
fi
STORAGE_PART="${BOOT_STORAGE}${PART_PREFIX}"

# now make up the configuration
echo "Mangling domain configuration: setting storage to ${BOOT_STORAGE}"
sed -i "s/STORAGE_PART/${STORAGE_PART}/g" $DOMA_CFG_FILE
