#!/bin/sh
# Change domain configuration to boot from storage configured by u-boot

MODE="$1"

DOMU_CFG_FILE="/etc/xen/domu.cfg"

# detect boot storage device
BOOT_STORAGE=`cat /proc/device-tree/boot_dev/device`
if [ -z "$BOOT_STORAGE" ] ; then
    BOOT_STORAGE=mmcblk1
    echo "WARNING! Using default storage: ${BOOT_STORAGE}"
fi

# Special case for NFS - we want to quite different cmd line
if [ $BOOT_STORAGE = nfs ] ; then
    SERVER_IP=`cat /proc/device-tree/boot_dev/nfs_server_ip  | tr -d '\000'`
    if [ -z "$SERVER_IP" ] ; then
        SERVER_IP="192.168.1.100"
        echo "WARNING! Using default server ip address ${SERVER_IP}"
    fi

    NFS_DIR=`cat /proc/device-tree/boot_dev/domu_nfs_dir | tr -d '\000'`
    if [ -z "$NFS_DIR" ] ; then
        NFS_DIR="/srv/domu"
        echo "WARNING! Using default NFS directory ${NFS_DIR}"
    fi

    BOOT_STR="nfs nfsroot=${SERVER_IP}:${NFS_DIR},vers=3 ip=dhcp"
    # Escape slahes ( / ->\/ )
    BOOT_STR=`echo "${BOOT_STR}" | sed "s/\//\\\\\\\\\//g"`

    echo "Mangling domain configuration: setting storage to network boot"

    REPLACE_DEVICE="xvda1"
    if [ "$MODE" == "enable_virtio" ]; then
        REPLACE_DEVICE="vda"
    fi

    sed -i "s/${REPLACE_DEVICE}/${BOOT_STR}/" $DOMU_CFG_FILE
    sed -i "s/disk = /# disk = /" $DOMU_CFG_FILE

    if [ "$MODE" == "enable_virtio" ]; then
        sed -i "/\[VIRTIO_DRIVE_CONFIGURATION\]/d" $DOMU_CFG_FILE
        sed -i "/\[QEMU_DRIVE_CONFIGURATION\]/d" $DOMU_CFG_FILE
    fi

    exit 0
fi

# guess partition prefix, e.g. "" for sda2 or "p" for mmcblk1p2
PART_PREFIX=""
if echo "${BOOT_STORAGE}" | grep -q 'mmc' ; then
   PART_PREFIX="p"
fi
STORAGE_PART="${BOOT_STORAGE}${PART_PREFIX}"

if [ "$MODE" == "enable_virtio" ]; then
    echo "Mangling QEMU configuration: setting up block device"
    # Both [VIRTIO_DRIVE_CONFIGURATION] and [QEMU_DRIVE_CONFIGURATION]
    # are last entries in corresponding properties.
    sed -i "s/\[VIRTIO_DRIVE_CONFIGURATION\]/'backend=DomD, type=virtio,device, transport=pci, bdf=0000:00:05.0, grant_usage=1, backend_type=qemu'/g" $DOMU_CFG_FILE
    sed -i "s/\[QEMU_DRIVE_CONFIGURATION\]/'-device', 'virtio-blk-pci,scsi=off,disable-legacy=on,iommu_platform=on,bus=pcie.0,addr=5,drive=image',\n\
'-drive', 'if=none,id=image,format=raw,file=\/dev\/STORAGE_PART3'/g" $DOMU_CFG_FILE
fi

# now make up the configuration
echo "Mangling domain configuration: setting storage to ${BOOT_STORAGE}"
sed -i "s/STORAGE_PART/${STORAGE_PART}/g" $DOMU_CFG_FILE
